// admin-profile.style.ts
import { createUseStyles } from 'react-jss';

export const useProfileStyles = createUseStyles({
    wrapper: {
        display: 'flex',
        gap: '3rem',
        flexWrap: 'wrap',
        padding: '2rem',
        justifyContent: 'center',
        alignItems: 'flex-start',
        background: '#f5f7ff',
        minHeight: '100vh',
    },
    profileCard: {
        flex: '0 0 300px',
        padding: '2rem',
        borderRadius: '15px',
        background: 'linear-gradient(145deg, #ffffff, #e6e9ff)',
        boxShadow: '0 10px 25px rgba(0,0,0,0.08)',
        textAlign: 'center',
    },
    avatarWrapper: {
        width: '140px',
        height: '140px',
        margin: '0 auto 1rem',
        borderRadius: '50%',
        padding: '5px',
        background: 'linear-gradient(135deg, #4f46e5, #8b5cf6)',
    },
    avatar: {
        width: '100%',
        height: '100%',
        borderRadius: '50%',
        objectFit: 'cover',
        border: '3px solid white',
    },
    name: {
        margin: '0.5rem 0',
        fontSize: '1.5rem',
        fontWeight: 600,
        color: '#1f2937',
    },
    email: {
        fontSize: '1rem',
        color: '#6b7280',
    },
    form: {
        flex: '1 1 400px',
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
        padding: '2rem',
        borderRadius: '15px',
        background: '#fff',
        boxShadow: '0 10px 25px rgba(0,0,0,0.05)',
    },
    formTitle: {
        marginBottom: '1rem',
        fontSize: '1.3rem',
        fontWeight: 600,
        color: '#4f46e5',
    },
    input: {
        padding: '0.8rem 1rem',
        borderRadius: '8px',
        border: '1px solid #d1d5db',
        fontSize: '1rem',
        '&:focus': {
            borderColor: '#4f46e5',
            outline: 'none',
            boxShadow: '0 0 0 2px rgba(79,70,229,0.2)',
        },
    },
    button: {
        padding: '0.8rem 1.5rem',
        borderRadius: '8px',
        border: 'none',
        background: '#4f46e5',
        color: '#fff',
        fontWeight: 600,
        fontSize: '1rem',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        '&:hover': {
            background: '#4338ca',
            transform: 'translateY(-2px)',
        },
    },
    status: {
        marginTop: '0.5rem',
        color: '#6b7280',
        fontSize: '0.95rem',
    },
    statusSuccess: {
        marginTop: '0.5rem',
        color: '#16a34a',
        fontSize: '0.95rem',
        fontWeight: 500,
    },
    statusError: {
        marginTop: '0.5rem',
        color: '#dc2626',
        fontSize: '0.95rem',
        fontWeight: 500,
    },
    loading: {
        fontSize: '1.2rem',
        textAlign: 'center',
        width: '100%',
        marginTop: '5rem',
        color: '#4f46e5',
    },
});
