import {IProduct} from "./products";

export let mockProducts: IProduct[] = [
    {
        id: 1,
        name: "Espresso",
        description: "Strong and bold espresso shot",
        photoUrl: "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a",
        price: 3,
        category: "Coffee",
        inStock: true,
    },
    {
        id: 2,
        name: "Cappuccino",
        description: "Espresso with steamed milk foam",
        photoUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
        price: 4,
        category: "Coffee",
        inStock: true,
    },
    {
        id: 3,
        name: "Latte",
        description: "Smooth coffee with milk",
        photoUrl: "https://images.unsplash.com/photo-1523942839745-7848d6c7baf2",
        price: 4.5,
        category: "Coffee",
        inStock: true,
    },
    {
        id: 4,
        name: "Americano",
        description: "Espresso with hot water",
        photoUrl: "https://images.unsplash.com/photo-1551030173-122aabc4489c",
        price: 3.5,
        category: "Coffee",
        inStock: true,
    },
    {
        id: 5,
        name: "Green Tea",
        description: "Refreshing green tea",
        photoUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574",
        price: 2.5,
        category: "Tea",
        inStock: true,
    },
    {
        id: 6,
        name: "Black Tea",
        description: "Classic black tea",
        photoUrl: "https://images.unsplash.com/photo-1518976024611-28bf4b48222e",
        price: 2,
        category: "Tea",
        inStock: false,
    },
    {
        id: 7,
        name: "Cheesecake",
        description: "Creamy classic cheesecake",
        photoUrl: "https://images.unsplash.com/photo-1542826438-8b6c7b7b7b30",
        price: 6,
        category: "Dessert",
        inStock: true,
    },
    {
        id: 8,
        name: "Chocolate Muffin",
        description: "Soft muffin with chocolate",
        photoUrl: "https://images.unsplash.com/photo-1605478448049-cc1cfc9b87b6",
        price: 3,
        category: "Dessert",
        inStock: true,
    },
    {
        id: 9,
        name: "Croissant",
        description: "Fresh French croissant",
        photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff",
        price: 2.8,
        category: "Bakery",
        inStock: true,
    },
    {
        id: 10,
        name: "Orange Juice",
        description: "Freshly squeezed orange juice",
        photoUrl: "https://images.unsplash.com/photo-1542444459-db63c27c2e85",
        price: 3.5,
        category: "Drink",
        inStock: true,
    },
];
